* Prefacio
  La conciencia de fetos no nacidos de seres celestiales han implorado ayuda de quien sea 
  que escuche y atienda su llamado, muchos escuchan, a pocos les importa,  eones pasaron
  hasta que una luz al final del tormentoso tunel se manifesto. Su nombre es Ihl, un ser gris, 
  mitad deminio mitad angel. Atendiendo su llamado con el proposito de ofrecerles un trato.

  Ihl les proveera acceso a nuestro mundo, y un lugar en el, naciendo como humanos, acambio ellos deben
  darle una cantidad de  sangre humana obtenida bajo las siguentes e inamovibles condiciones:

  ** Condiciones:
  - La sangre se les debe conferir de forma voluntaria y conciente.
  - No pueden hacer uso de engaños ni trampas de ningun tipo.
  
  Estos seres a quienes los llamaremos, animas, con el paso de los siglos desarrollaron habilidades unicas
  basadas en su inata capacidad de moldear energia. Aceptaron el trato de Ihl, entraron a nuestro mundo 
  en busca de proveedores de sangre, que les daria la libertad que tanto deseaban. Su estrategia es simple, 
  las animas ofreceran sus habilidades y servicios a los humanos que seleccionen, y acambio, ellos obtendran
  sangre por cada uso que se les de.

  Ihl, sonrie...

* Nombres tentativos para las animas:
  Quiltros -> Representacion humana de ojos cafe claro imponentes y tez marron
  

* Habilidades

** Kinesia
   Permite mover objetos usando solo su conciencia, permitiendole mover toda clase de objetos y a si mismo mientras el efecto dure.
   
*** Costo: 
    .20 unidades de sangre al iniciar y 1% de tu sangre actual cada minuto que la uses.

*** Enfriamiento
    45 segundos

*** Cualidades necesarias
    Inteligencia

** Seguro de vida
   Complejo, riesgozo pero muy util, el usuario acepta dar una enorme porcion no letal de sangre, a cambio
   cuando recibas un daño mortal, resucitaras con una curacion casi instantanea de todas tus heridas.
   
*** Costo 
    Costo 42% de tu sangre maxima.

*** Enfriamiento
    50 dias naturales de enfriamiento

*** Cualidades necesarias
    Valor
    Sacrificio

** Siempre a mi lado
   El usuario entrega una cantidad de sangre cada 15 segundos, a cambio, todos a 10 metros a su redonda ven acelerada drasticamente
   su regeneracion fisica y su salud mental. Requiere de un anfitrion de corazon generoso y desprendido.

*** Costo 
    50 ml de sangre cada 15 segundos

*** Enfriamiento
    Sin enfriamiento.

*** Cualidades necesarias
    Generosidad
    Desprendimiento

** Esclavista
   Doblegas la voluntad de un ente vivo, forzandolo a hacer lo que tu quieras durante el efecto. Tiene menos probabilidad de exito en seres
   con mentes fuertes.

*** Costo:
    Progresion de fibbonacci en mililitros cada .5 segundos hasta lograr el estado de esclavo

*** Enfriamiento:
    10 minutos

*** Cualidades necesarias
    Desconocidas

** Morador
   Teletransporta al usuario a una ubicacion que pueda ver fisicamente o en la que ya haya estado antes, canaliza un flujo de energia
   por 9 segundos para luego aparecer en la ubicacion deseada, puedes llevar acompañantes, pero aumenta el costo de la habilidad y su
   enfriamiento.

*** Costo:
    .5 Unidades de sangre mas 80ml por cada acompañante
*** Enfriamiento
    8 Horas + 1hora por cada acompañante
*** Cualidades necesarias
    Valor
    Curiosidad

** Zona kinematica

   Tras un gran grito definido por el jugador, todo a 100 metros a la redonda del usuario pasa a ser Kinematico, la gravedad, la inercia y el impulso se anulan.
   Todo pasa a estar a voluntad del anfritrion, siendo este, libre de moverse  en cualquier angulo y modificar todo a su gusto durante 
   9 minutos.

*** Costo
    1 unidad de sangre.
*** Enfriamiento
    24 horas
*** Cualidades necearias
    Buen humor
    Templanza

** Capacitividad 
   El anima habitara en ti y modificara un poco todo tu sistema nervioso, te condecera
   de una capacidad de movimiento unica, cada movimiento de tu cuerpo generara una carga 
   electrica la cual no tiene limite de almacenamiento. Puedes usar la carga como queras.

*** Costo:
    .5 Unidades de sangre por USO( Un uso concede 24 horas de Capacitividad). El costo en sangre se cobra a lo largo de 
    la duracion de la capacitividad.
*** Enfriamiento 
    8 horas.
*** Cualidades necesarias
    Inteligencia
    Serenidad

** Agua control
   La habilidad mas extraña, poderosa y peligrosa de todas las animas. Permite manipular el agua a nivel molecular, 
   otorgando al usuario la capacidad de  manipular todo ser viviente que posea agua en su interior, puede curar o matar todo lo que este
   a su control. Eso incluye al anfitrion.

*** Costo
    9ml de sangre por minuto, el costo se duplica cada minuto que se usa  la habilidad.

*** Enfriamiento
    SIN ENFRIAMIENTO

*** Cualidades necesarias:
    Desconocidas
    
    
